### ISSUE TITLE
Document Quality Control Parameter to be Output by the SOXS Pipeline

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/soxspipe#19]
All **calibration** data taken by SOXS could potentially be processed by the SOXS pipeline and used to 

1. monitor instrument health
2. monitor tends in the instrument health over time

We should be able to harvest all raw SOXS calibration data from the ESO archive (apart from those data closely associated with non-SOXS consortium proprietary science-frames).

Quality Control Level 1 (QC1) metrics are those parameters displayed on the VLT health check monitoring webpage (e.g.[XShooter](https://www.eso.org/observing/dfo/quality/XSHOOTER/reports/HEALTH/trend_report_BIAS_UVB_med_master_HC.html)). There are preset thresholds for a lot of these metrics which, if crossed, causes an alert warning to be issued.

Note: Quality Control Level 0 (QC0) is run on science data in real-time to make sure that exposure levels & observing constraints required by data PI have been met. I don't think we need to concern ourselves with these metrics.

For each SOXS pipeline recipe we should uses the XShooter QC pages (rather than the XS FDR document) to determine which QC1 metrics to output.

**TASKS**

For each recipe trawl the XShooter QC pages for a list of QC1 metrics to calculate. Give name, description and any algorithm required in the [overleaf design doc](https://www.overleaf.com/project/5d9dc9c54274d500011dd03e).

- [ ] `soxs_data_organiser`   
- [ ] `soxs_lingain`          
- [ ] `soxs_img_mflat`        
- [ ] `soxs_mbias`            
- [ ] `soxs_mdark`            
- [ ] `soxs_disp_solution`   
- [ ] `soxs_order_map`       
- [ ] `soxs_spatial_solution`
- [ ] `soxs_spec_mflat`      
- [ ] `soxs_straighten`      
- [ ] `soxs_line_check`      
- [ ] `soxs_nod`              
- [ ] `soxs_stare`            
- [ ] `soxs_offset`           
- [ ] `soxs_extract`          
- [ ] `soxs_response`         
- [ ] `soxs_merge`            
- [ ] `soxs_astrophot`

**Comment by thespacedoctor** [comment]
Here are the compiled QC checks - Marco has sent to the relevant people for comments. Anything back yet @marcolandoni ?

https://docs.google.com/spreadsheets/d/1DOlvSZmr4b3aLjZag_pyBxXYZykpAB2SKDZD3UJ236s/edit#gid=0

**Comment by thespacedoctor** [comment]
I think we can now start work on implementation and collection of QCs
