### ISSUE TITLE
JupyterHub instance for SOXS pipeline development

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/soxspipe#22]
We should have a VM soon which can be used for central development. JupyterHub will help us to write notebooks to convert logic into code. Once Marco and I both sign off on the logic we can then incorporate it into the python package.

**TASKS**

- [x] get VM spun up
- [x] install JupyterHub with the dependencies we currently need
- [x] get authentication working so we issue logins
