### ISSUE TITLE
Research optimal-extractions

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/soxspipe#24]
What kind of optimal-extractions are implemented in Python?

VI discussed a 2D method of providing a trace of the spectrum. Instead of just fitting a 1D cross-sectional gaussian fit and then moving along the trace, small 2D fits are made (i.e. 1D but also with a delta-lambda). This helps to follow the trace across merged orders especially when fringing is an issue.

The big revelation for us that is surprisingly unclear from all the XShooter docs is that in the XShooter pipeline the extraction is done on the curved, pre-rectified images. Obviously this makes a lot of sense as the rectification introduces correlated noise into the spectrum.

**TASKS**

- [ ] what python implementations of optimal-extract exist?
- [ ] what does pypeit do?
- [ ] what about Jonatan Selsing method?
