### ISSUE TITLE
Automate testing, integration and deployment of soxs pipeline code with a Jenkins CI/CD server

### ISSUE THREAD

**Issue by thespacedoctor** [thespacedoctor/soxspipe#39]
The purpose of the continuous integration server is to completely automate the testing of project code with every push to github (running of test becomes very time consuming especially as a code-base grows). I have built a Jenkins server (via ansible playbooks) and deployed it here:

<http://167.99.90.204:8080>

Access can be granted to whoever is interested.

**TASKS**

- [x] integrate build alerts with into slack to report on build success and failures
- [x] allow code in *feature* or *hotfix* branches to be automatically merged to the development branch of the code if all tests pass
- [x] allow code in *release* branches to be automatically merged to the development & master branches of the code if all tests pass
- [x] automate the deploy to pypi of all tests in the master branch pass
